export const countryCodes = [
  { name: "United States", dial_code: "+1", code: "US" },
  { name: "United Kingdom", dial_code: "+44", code: "GB" },
  { name: "Canada", dial_code: "+1", code: "CA" },
  { name: "Australia", dial_code: "+61", code: "AU" },
  { name: "Germany", dial_code: "+49", code: "DE" },
  { name: "France", dial_code: "+33", code: "FR" },
  { name: "India", dial_code: "+91", code: "IN" },
  { name: "Brazil", dial_code: "+55", code: "BR" },
  { name: "Japan", dial_code: "+81", code: "JP" },
  { name: "China", dial_code: "+86", code: "CN" },
  { name: "Afghanistan", dial_code: "+93", code: "AF" },
  { name: "Argentina", dial_code: "+54", code: "AR" },
  { name: "Belgium", dial_code: "+32", code: "BE" },
  { name: "Chile", dial_code: "+56", code: "CL" },
  { name: "Colombia", dial_code: "+57", code: "CO" },
  { name: "Denmark", dial_code: "+45", code: "DK" },
  { name: "Egypt", dial_code: "+20", code: "EG" },
  { name: "Finland", dial_code: "+358", code: "FI" },
  { name: "Greece", dial_code: "+30", code: "GR" },
  { name: "Hong Kong", dial_code: "+852", code: "HK" },
  { name: "Hungary", dial_code: "+36", code: "HU" },
  { name: "Iceland", dial_code: "+354", code: "IS" },
  { name: "Indonesia", dial_code: "+62", code: "ID" },
  { name: "Iran", dial_code: "+98", code: "IR" },
  { name: "Iraq", dial_code: "+964", code: "IQ" },
  { name: "Ireland", dial_code: "+353", code: "IE" },
  { name: "Israel", dial_code: "+972", code: "IL" },
  { name: "Italy", dial_code: "+39", code: "IT" },
  { name: "Mexico", dial_code: "+52", code: "MX" },
  { name: "Netherlands", dial_code: "+31", code: "NL" },
  { name: "New Zealand", dial_code: "+64", code: "NZ" },
  { name: "Norway", dial_code: "+47", code: "NO" },
  { name: "Pakistan", dial_code: "+92", code: "PK" },
  { name: "Philippines", dial_code: "+63", code: "PH" },
  { name: "Poland", dial_code: "+48", code: "PL" },
  { name: "Portugal", dial_code: "+351", code: "PT" },
  { name: "Russia", dial_code: "+7", code: "RU" },
  { name: "Saudi Arabia", dial_code: "+966", code: "SA" },
  { name: "Singapore", dial_code: "+65", code: "SG" },
  { name: "South Africa", dial_code: "+27", code: "ZA" },
  { name: "South Korea", dial_code: "+82", code: "KR" },
  { name: "Spain", dial_code: "+34", code: "ES" },
  { name: "Sweden", dial_code: "+46", code: "SE" },
  { name: "Switzerland", dial_code: "+41", code: "CH" },
  { name: "Thailand", dial_code: "+66", code: "TH" },
  { name: "Turkey", dial_code: "+90", code: "TR" },
  { name: "Ukraine", dial_code: "+380", code: "UA" },
  { name: "United Arab Emirates", dial_code: "+971", code: "AE" },
  { name: "Vietnam", dial_code: "+84", code: "VN" },
];